# Generated by Django 5.1.4 on 2025-01-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yassin', '0002_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='age',
            field=models.IntegerField(),
        ),
    ]
